# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Naturalflood.py
# Created on: 2017-05-23 07:55:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Naturalflood <Workspace> <Flooding> <Crops> <WRP> <State> <Natural_flood_shp> <MAV> <WorkspaceGDB> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os, sys, getopt
from arcpy.sa import *

arcpy.env.overwriteOutput = True;

def checkField (shp, field):
        fields = arcpy.ListFields(shp, field)
        if len(fields) !=1:
                return True
        else:
                return False

        
# Setup model specifics
def prepFlood (scratchgdb, pct, flood):


# Script arguments from ArcGIS.  Keeping these and setting them = to input parameters

        try:
                if arcpy.CheckExtension("Spatial") == "Available":
                        arcpy.CheckOutExtension("Spatial")
                else:
                        print("Spatial analyst license not available")
                        sys.exit(2)
        except Exception, e:
                print("Can't acquire spatial analyst license: ", e)
                sys.exit(2)

        print "Calculating flood"        
        rasFlood = Raster(flood)
        outFlood = Con(rasFlood > pct, 1, 0)
        outFlood.save(os.path.join(scratchgdb, "floodSetup"))
        print("Everything good")
        




